<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="coverlet.collector" Version="6.0.4" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.1" />
		<PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.1" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
		<PackageReference Include="Moq" Version="4.20.72" />
		<PackageReference Include="OSK.Extensions.Object.DeepEquals" Version="1.1.2" />
		<PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
		<PackageReference Include="xunit.v3" Version="3.2.2" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\OSK.Inputs\OSK.Inputs.csproj" />
	</ItemGroup>

</Project>
