name: Package Cleanup

on:
  workflow_dispatch:
    inputs:
      keepCount:
        description: 'The number of versions to keep'
        required: false
        default: '2'
  registry_package:
    types: [published]

jobs:
  CleanupPackages:

    runs-on: ubuntu-latest
  
    steps:
      - name: Delete old packages
        uses: SmartsquareGmbH/delete-old-packages@v0.8.1
        with:
          keep: ${{ github.event.inputs.keepCount }}
          names: |
            ${{ github.event.repository.name }}