name: Upload dotnet package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Get Pull Request Number and Commit Number
        id: get_version
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          COMMIT_NUMBER="${{ github.run_number }}"
          echo "PACKAGE_VERSION=0.0.0-OSK-${PR_NUMBER}-${COMMIT_NUMBER}-beta" >> "$GITHUB_OUTPUT" 
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: '8.0.x' # SDK Version to use.
          source-url: https://nuget.pkg.github.com/OpenSourceKingdom/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: dotnet build --configuration Release ./src /p:Version=${{ steps.get_version.outputs.PACKAGE_VERSION }}
      - name: Create the package
        run: dotnet pack --configuration Release ./src -o . /p:Version=${{ steps.get_version.outputs.PACKAGE_VERSION }}
      - name: Publish the package to GPR
        run: dotnet nuget push ./*.nupkg --api-key ${{secrets.GITHUB_TOKEN}}